[theme]
base="light"
primaryColor="#8BC34A"             # your bright “call-to-action” green
backgroundColor="#D7E9A9"          # the pale overall canvas
secondaryBackgroundColor="#E8F5E9"  # cards, panels
textColor="#2E7D32"                # dark-green text
font="sans serif"
